### ISSUE TITLE
Running `yarn start:ios` throws `stream.arrayBuffer is not a function` error

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-sdk-js-tests#223]
## Describe the bug

Running `yarn start:ios` throws `stream.arrayBuffer is not a function` error

## Steps to reproduce

Follow instructions for running SDK call in iOS

#### Observed behavior

SDK call throws `stream.arrayBuffer is not a function` error

<details>
<summary>Screenshot</summary>

<img width="561" alt="screenshot-ios-fail" src="https://github.com/user-attachments/assets/d980761d-1157-486c-9d0f-166b26b3e69a" />

</details>

#### Expected behavior

SDK call to be successful

<details>
<summary>Screenshot</summary>

<img width="561" alt="screenshot-ios" src="https://github.com/user-attachments/assets/73eb34c4-96bb-4237-a5e3-71d7b714507d" />

</details>

## Additional context

Likely introduced in lockfile update https://github.com/aws-samples/aws-sdk-js-tests/commit/1218870cd2e14a80dde865f2b90b06ea775c5771

**Comment by trivikr** [comment]
Error from console for reference

```console
 LOG  Running "reactnative" with {"rootTag":1,"initialProps":{"concurrentRoot":false}}
 ERROR  {"$metadata": {"attempts": 1, "totalRetryDelay": 0}, "message": "stream.arrayBuffer is not a function (it is undefined)
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.", "name": "TypeError", "stack": "TypeError: stream.arrayBuffer is not a function (it is undefined)
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=ios&dev=true&lazy=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.reactnative:147810:55)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=ios&dev=true&lazy=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.reactnative:5593:19)
```

**Comment by trivikr** [comment]
The issue seems to be introduced in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.686.0

**Comment by trivikr** [comment]
Possibly related to https://github.com/aws/aws-sdk-js-v3/issues/6733

**Comment by trivikr** [comment]
Probably introduced by https://github.com/smithy-lang/smithy-typescript/pull/1179 which was released in `@smithy/node-http-handler@4.0.0`

**Comment by trivikr** [comment]
Fixed by lockfile update in https://github.com/aws-samples/aws-sdk-js-tests/pull/227
